# Generated by Django 5.1.4 on 2024-12-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
            ],
        ),
    ]
